export const colors = {
  surface: '#f5fced', // organic light-greenish surface background
  surfaceDim: '#d5dcce',
  surfaceBright: '#f5fced',
  surfaceContainerLowest: '#ffffff',
  surfaceContainerLow: '#eff6e7',
  surfaceContainer: '#e9f0e1',
  surfaceContainerHigh: '#e3ebdc',
  surfaceContainerHighest: '#dee5d6',
  onSurface: '#171d14',
  onSurfaceVariant: '#40493d',
  inverseSurface: '#2c3228',
  inverseOnSurface: '#ecf3e4',
  outline: '#707a6c',
  outlineVariant: '#bfcaba',
  surfaceTint: '#1b6d24',
  primary: '#012d1d',
  onPrimary: '#ffffff',
  primaryContainer: '#2e7d32', // mockup grass green
  onPrimaryContainer: '#cbffc2', // mockup lime green
  inversePrimary: '#a5d0b9',
  secondary: '#0e6c4a',
  onSecondary: '#ffffff',
  secondaryContainer: '#a0f4c8',
  onSecondaryContainer: '#19724f',
  tertiary: '#002d1a',
  onTertiary: '#ffffff',
  tertiaryContainer: '#1a432e',
  onTertiaryContainer: '#84b095',
  error: '#ba1a1a',
  onError: '#ffffff',
  errorContainer: '#ffdad6',
  onErrorContainer: '#93000a',
};
